apiVersion: v1  # 不要改动
kind: Plugin  # 不要改动
metadata:
  # author 和 name 唯一确定一个插件
  author: lovefan-fan  # 插件作者，修改为你的名称
  name: WechatImageDownloader  # 插件名称，修改为你的插件名称
  repository: 'https://github.com/lovefan-fan/download_wx_Image'  # 插件仓库地址，修改为你的插件 GitHub 仓库地址
  version: 0.2  # 插件版本，修改为你的插件版本
  description:  # 插件简介，修改为你的插件简介，支持多语言
    en_US: Plugin for downloading images from WeChat articles
    zh_CN: 微信文章图片下载插件
  label:  # 插件显示名称，支持多语言。在 WebUI 上会显示对应语言的 label
    en_US: Wechat Image Downloader
    zh_CN: 微信图片下载器
execution:
  python:
    path: main.py  # 插件主程序路径，必须与上方插件入口代码的文件名相同
    attr: MyPlugin  # 插件类名，必须与上方代码中声明的类名相同
